// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { StudyServiceCreateData, StudyServiceCreateErrors, StudyServiceCreateResponses, StudyServiceDeleteData, StudyServiceDeleteErrors, StudyServiceDeleteResponses, StudyServiceGetData, StudyServiceGetErrors, StudyServiceGetResponses, StudyServiceListData, StudyServiceListErrors, StudyServiceListResponses, StudyServiceSummaryData, StudyServiceSummaryErrors, StudyServiceSummaryResponses, StudyServiceUpdateData, StudyServiceUpdateErrors, StudyServiceUpdateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List all studies
 *
 * Returns a list of all UX research studies
 */
export const studyServiceList = <ThrowOnError extends boolean = false>(options?: Options<StudyServiceListData, ThrowOnError>) => (options?.client ?? client).get<StudyServiceListResponses, StudyServiceListErrors, ThrowOnError>({ url: '/', ...options });

/**
 * Create a new study
 *
 * Creates a new UX research study
 */
export const studyServiceCreate = <ThrowOnError extends boolean = false>(options: Options<StudyServiceCreateData, ThrowOnError>) => (options.client ?? client).post<StudyServiceCreateResponses, StudyServiceCreateErrors, ThrowOnError>({
    url: '/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a study
 *
 * Deletes a UX research study by its ID
 */
export const studyServiceDelete = <ThrowOnError extends boolean = false>(options: Options<StudyServiceDeleteData, ThrowOnError>) => (options.client ?? client).delete<StudyServiceDeleteResponses, StudyServiceDeleteErrors, ThrowOnError>({ url: '/{id}', ...options });

/**
 * Get a study by ID
 *
 * Returns a single UX research study by its ID
 */
export const studyServiceGet = <ThrowOnError extends boolean = false>(options: Options<StudyServiceGetData, ThrowOnError>) => (options.client ?? client).get<StudyServiceGetResponses, StudyServiceGetErrors, ThrowOnError>({ url: '/{id}', ...options });

/**
 * Update a study
 *
 * Partially updates an existing UX research study
 */
export const studyServiceUpdate = <ThrowOnError extends boolean = false>(options: Options<StudyServiceUpdateData, ThrowOnError>) => (options.client ?? client).patch<StudyServiceUpdateResponses, StudyServiceUpdateErrors, ThrowOnError>({
    url: '/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get studies summary
 *
 * Returns aggregated statistics about all UX research studies including total count, average duration, and breakdown by status and study type
 */
export const studyServiceSummary = <ThrowOnError extends boolean = false>(options?: Options<StudyServiceSummaryData, ThrowOnError>) => (options?.client ?? client).get<StudyServiceSummaryResponses, StudyServiceSummaryErrors, ThrowOnError>({ url: '/summary', ...options });
