// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://ux-research-api.azurewebsites.net' | 'http://localhost:3000' | (string & {});
};

/**
 * A UX research study
 */
export type Study = {
    /**
     * Auto-generated unique identifier
     */
    readonly id: string;
    /**
     * Name of the study
     */
    title: string;
    /**
     * Type of the UX research study
     */
    studyType: 'Usability' | 'Interview' | 'Survey' | 'A/B Test';
    /**
     * Current status of the study
     */
    status: 'Planned' | 'Active' | 'Completed';
    /**
     * Name of the researcher running the study
     */
    researcherName: string;
    /**
     * Duration of each session in minutes
     */
    durationMinutes: number;
    /**
     * Any additional notes about the study
     */
    notes?: string;
};

/**
 * Data required to create a new UX research study
 */
export type StudyCreate = {
    /**
     * Name of the study
     */
    title: string;
    /**
     * Type of the UX research study
     */
    studyType: 'Usability' | 'Interview' | 'Survey' | 'A/B Test';
    /**
     * Current status of the study
     */
    status: 'Planned' | 'Active' | 'Completed';
    /**
     * Name of the researcher running the study
     */
    researcherName: string;
    /**
     * Duration of each session in minutes
     */
    durationMinutes: number;
    /**
     * Any additional notes about the study
     */
    notes?: string;
};

/**
 * Data for partially updating an existing UX research study
 */
export type StudyUpdate = {
    /**
     * Name of the study
     */
    title?: string;
    /**
     * Type of the UX research study
     */
    studyType?: 'Usability' | 'Interview' | 'Survey' | 'A/B Test';
    /**
     * Current status of the study
     */
    status?: 'Planned' | 'Active' | 'Completed';
    /**
     * Name of the researcher running the study
     */
    researcherName?: string;
    /**
     * Duration of each session in minutes
     */
    durationMinutes?: number;
    /**
     * Any additional notes about the study
     */
    notes?: string;
};

/**
 * A UX research study
 */
export type StudyWritable = {
    /**
     * Name of the study
     */
    title: string;
    /**
     * Type of the UX research study
     */
    studyType: 'Usability' | 'Interview' | 'Survey' | 'A/B Test';
    /**
     * Current status of the study
     */
    status: 'Planned' | 'Active' | 'Completed';
    /**
     * Name of the researcher running the study
     */
    researcherName: string;
    /**
     * Duration of each session in minutes
     */
    durationMinutes: number;
    /**
     * Any additional notes about the study
     */
    notes?: string;
};

export type StudyServiceListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type StudyServiceListErrors = {
    /**
     * Bad request
     */
    400: unknown;
};

export type StudyServiceListResponses = {
    /**
     * A list of studies retrieved successfully
     */
    200: unknown;
};

export type StudyServiceCreateData = {
    body: StudyCreate;
    path?: never;
    query?: never;
    url: '/';
};

export type StudyServiceCreateErrors = {
    /**
     * Bad request
     */
    400: unknown;
};

export type StudyServiceCreateResponses = {
    /**
     * Study created successfully
     */
    201: unknown;
};

export type StudyServiceDeleteData = {
    body?: never;
    path: {
        /**
         * The unique ID of the study
         */
        id: string;
    };
    query?: never;
    url: '/{id}';
};

export type StudyServiceDeleteErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Study not found
     */
    404: unknown;
};

export type StudyServiceDeleteResponses = {
    /**
     * Study deleted successfully
     */
    200: unknown;
};

export type StudyServiceGetData = {
    body?: never;
    path: {
        /**
         * The unique ID of the study
         */
        id: string;
    };
    query?: never;
    url: '/{id}';
};

export type StudyServiceGetErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Study not found
     */
    404: unknown;
};

export type StudyServiceGetResponses = {
    /**
     * Study retrieved successfully
     */
    200: unknown;
};

export type StudyServiceUpdateData = {
    body: StudyUpdate;
    path: {
        /**
         * The unique ID of the study
         */
        id: string;
    };
    query?: never;
    url: '/{id}';
};

export type StudyServiceUpdateErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Study not found
     */
    404: unknown;
};

export type StudyServiceUpdateResponses = {
    /**
     * Study updated successfully
     */
    200: unknown;
};

export type StudyServiceSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/summary';
};

export type StudyServiceSummaryErrors = {
    /**
     * Bad request
     */
    400: unknown;
};

export type StudyServiceSummaryResponses = {
    /**
     * Summary retrieved successfully
     */
    200: unknown;
};
