// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://backend-ux.azurewebsites.net' | 'http://localhost:3000' | (string & {});
};

/**
 * A UX research study record.
 */
export type Study = {
    /**
     * Auto-generated unique identifier
     */
    readonly id: string;
    /**
     * Title of the research study
     */
    title: string;
    /**
     * The research method used
     */
    methodology: 'Usability Testing' | 'Interview' | 'Survey' | 'Card Sorting' | 'A/B Testing';
    /**
     * Current status of the study
     */
    status: 'Planned' | 'In Progress' | 'Completed';
    /**
     * Number of participants in the study
     */
    participantCount: number;
    /**
     * Duration of each session in minutes
     */
    durationMinutes: number;
    /**
     * Name of the lead researcher
     */
    researcherName: string;
};

/**
 * Fields required to create a new study. ID is auto-generated.
 */
export type StudyCreate = {
    /**
     * Title of the research study
     */
    title: string;
    /**
     * The research method used
     */
    methodology: 'Usability Testing' | 'Interview' | 'Survey' | 'Card Sorting' | 'A/B Testing';
    /**
     * Current status of the study
     */
    status: 'Planned' | 'In Progress' | 'Completed';
    /**
     * Number of participants
     */
    participantCount: number;
    /**
     * Duration of each session in minutes
     */
    durationMinutes: number;
    /**
     * Name of the lead researcher
     */
    researcherName: string;
};

/**
 * All fields optional — only provided fields will be updated.
 */
export type StudyUpdate = {
    /**
     * Title of the research study
     */
    title?: string;
    /**
     * The research method used
     */
    methodology?: 'Usability Testing' | 'Interview' | 'Survey' | 'Card Sorting' | 'A/B Testing';
    /**
     * Current status of the study
     */
    status?: 'Planned' | 'In Progress' | 'Completed';
    /**
     * Number of participants
     */
    participantCount?: number;
    /**
     * Duration of each session in minutes
     */
    durationMinutes?: number;
    /**
     * Name of the lead researcher
     */
    researcherName?: string;
};

/**
 * Aggregated statistics across all studies.
 */
export type Summary = {
    /**
     * Total number of studies
     */
    totalStudies?: number;
    /**
     * Average number of participants across all studies
     */
    averageParticipants?: number;
    /**
     * Count of studies grouped by methodology
     */
    byMethodology?: {
        [key: string]: number;
    };
};

/**
 * Standard error response.
 */
export type Error = {
    /**
     * HTTP status code
     */
    code?: number;
    /**
     * Human-readable error message
     */
    message?: string;
};

/**
 * A UX research study record.
 */
export type StudyWritable = {
    /**
     * Title of the research study
     */
    title: string;
    /**
     * The research method used
     */
    methodology: 'Usability Testing' | 'Interview' | 'Survey' | 'Card Sorting' | 'A/B Testing';
    /**
     * Current status of the study
     */
    status: 'Planned' | 'In Progress' | 'Completed';
    /**
     * Number of participants in the study
     */
    participantCount: number;
    /**
     * Duration of each session in minutes
     */
    durationMinutes: number;
    /**
     * Name of the lead researcher
     */
    researcherName: string;
};

export type StudyServiceListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type StudyServiceListResponses = {
    /**
     * A list of studies
     */
    200: Array<Study>;
};

export type StudyServiceListResponse = StudyServiceListResponses[keyof StudyServiceListResponses];

export type StudyServiceCreateData = {
    body: StudyCreate;
    path?: never;
    query?: never;
    url: '/';
};

export type StudyServiceCreateErrors = {
    /**
     * Validation error
     */
    400: Error;
};

export type StudyServiceCreateError = StudyServiceCreateErrors[keyof StudyServiceCreateErrors];

export type StudyServiceCreateResponses = {
    /**
     * Study created successfully
     */
    201: Study;
};

export type StudyServiceCreateResponse = StudyServiceCreateResponses[keyof StudyServiceCreateResponses];

export type StudyServiceSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/summary';
};

export type StudyServiceSummaryResponses = {
    /**
     * Summary statistics
     */
    200: Summary;
};

export type StudyServiceSummaryResponse = StudyServiceSummaryResponses[keyof StudyServiceSummaryResponses];

export type StudyServiceDeleteData = {
    body?: never;
    path: {
        /**
         * The unique ID of the study
         */
        id: string;
    };
    query?: never;
    url: '/{id}';
};

export type StudyServiceDeleteErrors = {
    /**
     * Study not found
     */
    404: Error;
};

export type StudyServiceDeleteError = StudyServiceDeleteErrors[keyof StudyServiceDeleteErrors];

export type StudyServiceDeleteResponses = {
    /**
     * Study deleted
     */
    200: {
        message?: string;
    };
};

export type StudyServiceDeleteResponse = StudyServiceDeleteResponses[keyof StudyServiceDeleteResponses];

export type StudyServiceGetData = {
    body?: never;
    path: {
        /**
         * The unique ID of the study
         */
        id: string;
    };
    query?: never;
    url: '/{id}';
};

export type StudyServiceGetErrors = {
    /**
     * Study not found
     */
    404: Error;
};

export type StudyServiceGetError = StudyServiceGetErrors[keyof StudyServiceGetErrors];

export type StudyServiceGetResponses = {
    /**
     * The study
     */
    200: Study;
};

export type StudyServiceGetResponse = StudyServiceGetResponses[keyof StudyServiceGetResponses];

export type StudyServiceUpdateData = {
    body: StudyUpdate;
    path: {
        /**
         * The unique ID of the study
         */
        id: string;
    };
    query?: never;
    url: '/{id}';
};

export type StudyServiceUpdateErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Study not found
     */
    404: Error;
};

export type StudyServiceUpdateError = StudyServiceUpdateErrors[keyof StudyServiceUpdateErrors];

export type StudyServiceUpdateResponses = {
    /**
     * Updated study
     */
    200: Study;
};

export type StudyServiceUpdateResponse = StudyServiceUpdateResponses[keyof StudyServiceUpdateResponses];
